images:
  app: iot-app:2.0

externalDependencies:
  enabled: false

managementApi:
  enabled: true

iotCore:
  enabled: true

telemetryIngestor:
  enabled: true

deviceWorker:
  enabled: true

demo:
  enabled: true

postgres:
  enabled: true

kafka:
  enabled: true

emqx:
  enabled: true

tdengine:
  enabled: true

prometheus:
  enabled: true
  extraScrapeTargets: []
