images:
  app: iot-app:2.0
  postgres: postgres:15-alpine
  kafka: bitnamilegacy/kafka:latest
  emqx: emqx/emqx-enterprise:latest
  tdengine: tdengine/tdengine:latest
  prometheus: prom/prometheus:v2.55.1

externalDependencies:
  enabled: true
  hostGatewayIP: 192.168.65.254
  postgresDsn: postgres://iot:iot123@192.168.65.254:5432/iot?sslmode=disable
  kafkaBrokers: 192.168.65.254:9092
  emqxUrl: tcp://192.168.65.254:1883
  tdengineDsn: root:taosdata@http(192.168.65.254:6041)/iot
  etcdHosts: 192.168.65.254:2379
  etcdKey: iot/core-rpc
  wait:
    postgresHost: 192.168.65.254
    postgresPort: 5432
    kafkaHost: 192.168.65.254
    kafkaPort: 9092
    emqxHost: 192.168.65.254
    emqxPort: 1883
    tdengineHost: 192.168.65.254
    tdenginePort: 6041
    etcdHost: 192.168.65.254
    etcdPort: 2379

admin:
  enabled: true

coreRpc:
  enabled: true

ingress:
  enabled: true

worker:
  enabled: true

demo:
  enabled: false

postgres:
  enabled: false
  storage: 1Gi

kafka:
  enabled: false
  storage: 1Gi

emqx:
  enabled: false
  storage: 1Gi

tdengine:
  enabled: false
  storage: 1Gi

prometheus:
  enabled: false
  nodePort: 30900
  retention: 7d
  extraScrapeTargets:
    - jobName: demo-docker
      targets:
        - host.docker.internal:18084
