global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: management-api
    static_configs:
      - targets:
          - k8s-forward-management-api-metrics:18090

  - job_name: telemetry-ingestor
    static_configs:
      - targets:
          - k8s-forward-telemetry-ingestor:18081

  - job_name: device-worker
    static_configs:
      - targets:
          - k8s-forward-device-worker:18082

  - job_name: iot-core
    static_configs:
      - targets:
          - k8s-forward-iot-core:18091

  - job_name: demo-docker
    static_configs:
      - targets:
          - demo:8080
