// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.0
// source: proto/core/v1/core.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_proto_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Device struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_proto_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *Device) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Device) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Device) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Device) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Device) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	LastSeenAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_proto_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceStatus) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeviceStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatus) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *DeviceStatus) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

type TelemetryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	ReceivedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRecord) Reset() {
	*x = TelemetryRecord{}
	mi := &file_proto_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRecord) ProtoMessage() {}

func (x *TelemetryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRecord.ProtoReflect.Descriptor instead.
func (*TelemetryRecord) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *TelemetryRecord) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *TelemetryRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TelemetryRecord) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TelemetryRecord) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *TelemetryRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TelemetryRecord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *TelemetryRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TelemetryRecord) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Command) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Command) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Command) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTenantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Secret        string                 `protobuf:"bytes,4,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDeviceRequest) Reset() {
	*x = CreateDeviceRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDeviceRequest) ProtoMessage() {}

func (x *CreateDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDeviceRequest.ProtoReflect.Descriptor instead.
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDeviceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateDeviceRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateDeviceRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type GetDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceRequest) Reset() {
	*x = GetDeviceRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceRequest) ProtoMessage() {}

func (x *GetDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *GetDeviceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        *Device                `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceResponse) Reset() {
	*x = GetDeviceResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceResponse) ProtoMessage() {}

func (x *GetDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *GetDeviceResponse) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

type GetDeviceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatusRequest) Reset() {
	*x = GetDeviceStatusRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatusRequest) ProtoMessage() {}

func (x *GetDeviceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *GetDeviceStatusRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetDeviceStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *DeviceStatus          `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceStatusResponse) Reset() {
	*x = GetDeviceStatusResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceStatusResponse) ProtoMessage() {}

func (x *GetDeviceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *GetDeviceStatusResponse) GetStatus() *DeviceStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{11}
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{13}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*Device              `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{14}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ListTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTelemetryRequest) Reset() {
	*x = ListTelemetryRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTelemetryRequest) ProtoMessage() {}

func (x *ListTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTelemetryRequest.ProtoReflect.Descriptor instead.
func (*ListTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{15}
}

func (x *ListTelemetryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListTelemetryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ListTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*TelemetryRecord     `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTelemetryResponse) Reset() {
	*x = ListTelemetryResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTelemetryResponse) ProtoMessage() {}

func (x *ListTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTelemetryResponse.ProtoReflect.Descriptor instead.
func (*ListTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{16}
}

func (x *ListTelemetryResponse) GetRecords() []*TelemetryRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type IngestTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         string                 `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTelemetryRequest) Reset() {
	*x = IngestTelemetryRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTelemetryRequest) ProtoMessage() {}

func (x *IngestTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTelemetryRequest.ProtoReflect.Descriptor instead.
func (*IngestTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{17}
}

func (x *IngestTelemetryRequest) GetMsgId() string {
	if x != nil {
		return x.MsgId
	}
	return ""
}

func (x *IngestTelemetryRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IngestTelemetryRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *IngestTelemetryRequest) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *IngestTelemetryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IngestTelemetryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *IngestTelemetryRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type IngestTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *TelemetryRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestTelemetryResponse) Reset() {
	*x = IngestTelemetryResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestTelemetryResponse) ProtoMessage() {}

func (x *IngestTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestTelemetryResponse.ProtoReflect.Descriptor instead.
func (*IngestTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{18}
}

func (x *IngestTelemetryResponse) GetRecord() *TelemetryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type RecordTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Telemetry     *TelemetryRecord       `protobuf:"bytes,1,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTelemetryRequest) Reset() {
	*x = RecordTelemetryRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTelemetryRequest) ProtoMessage() {}

func (x *RecordTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTelemetryRequest.ProtoReflect.Descriptor instead.
func (*RecordTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{19}
}

func (x *RecordTelemetryRequest) GetTelemetry() *TelemetryRecord {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type RecordTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *TelemetryRecord       `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTelemetryResponse) Reset() {
	*x = RecordTelemetryResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTelemetryResponse) ProtoMessage() {}

func (x *RecordTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTelemetryResponse.ProtoReflect.Descriptor instead.
func (*RecordTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{20}
}

func (x *RecordTelemetryResponse) GetRecord() *TelemetryRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type CreateCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandRequest) Reset() {
	*x = CreateCommandRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandRequest) ProtoMessage() {}

func (x *CreateCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{21}
}

func (x *CreateCommandRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateCommandRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CreateCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommandResponse) Reset() {
	*x = CreateCommandResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommandResponse) ProtoMessage() {}

func (x *CreateCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommandResponse.ProtoReflect.Descriptor instead.
func (*CreateCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{22}
}

func (x *CreateCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type ListCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsRequest) Reset() {
	*x = ListCommandsRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsRequest) ProtoMessage() {}

func (x *ListCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsRequest.ProtoReflect.Descriptor instead.
func (*ListCommandsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{23}
}

type ListCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommandsResponse) Reset() {
	*x = ListCommandsResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommandsResponse) ProtoMessage() {}

func (x *ListCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommandsResponse.ProtoReflect.Descriptor instead.
func (*ListCommandsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{24}
}

func (x *ListCommandsResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type GetCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandRequest) Reset() {
	*x = GetCommandRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandRequest) ProtoMessage() {}

func (x *GetCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandRequest.ProtoReflect.Descriptor instead.
func (*GetCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{25}
}

func (x *GetCommandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommandResponse) Reset() {
	*x = GetCommandResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommandResponse) ProtoMessage() {}

func (x *GetCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommandResponse.ProtoReflect.Descriptor instead.
func (*GetCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{26}
}

func (x *GetCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type AckCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCommandRequest) Reset() {
	*x = AckCommandRequest{}
	mi := &file_proto_core_v1_core_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommandRequest) ProtoMessage() {}

func (x *AckCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommandRequest.ProtoReflect.Descriptor instead.
func (*AckCommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{27}
}

func (x *AckCommandRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckCommandRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AckCommandRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type AckCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *Command               `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCommandResponse) Reset() {
	*x = AckCommandResponse{}
	mi := &file_proto_core_v1_core_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommandResponse) ProtoMessage() {}

func (x *AckCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_core_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommandResponse.ProtoReflect.Descriptor instead.
func (*AckCommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_core_proto_rawDescGZIP(), []int{28}
}

func (x *AckCommandResponse) GetCommand() *Command {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_proto_core_v1_core_proto protoreflect.FileDescriptor

const file_proto_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x18proto/core/v1/core.proto\x12\acore.v1\x1a\x1fgoogle/protobuf/timestamp.proto\",\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb4\x01\n" +
	"\x06Device\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x9e\x01\n" +
	"\fDeviceStatus\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\x12<\n" +
	"\flast_seen_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\"\xf7\x01\n" +
	"\x0fTelemetryRecord\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12;\n" +
	"\vreceived_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\"\xfb\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"9\n" +
	"\x13CreateTenantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x86\x01\n" +
	"\x13CreateDeviceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06secret\x18\x04 \x01(\tR\x06secret\"L\n" +
	"\x10GetDeviceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"<\n" +
	"\x11GetDeviceResponse\x12'\n" +
	"\x06device\x18\x01 \x01(\v2\x0f.core.v1.DeviceR\x06device\"R\n" +
	"\x16GetDeviceStatusRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"H\n" +
	"\x17GetDeviceStatusResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\v2\x15.core.v1.DeviceStatusR\x06status\"\x14\n" +
	"\x12ListTenantsRequest\"@\n" +
	"\x13ListTenantsResponse\x12)\n" +
	"\atenants\x18\x01 \x03(\v2\x0f.core.v1.TenantR\atenants\"\x14\n" +
	"\x12ListDevicesRequest\"@\n" +
	"\x13ListDevicesResponse\x12)\n" +
	"\adevices\x18\x01 \x03(\v2\x0f.core.v1.DeviceR\adevices\"P\n" +
	"\x14ListTelemetryRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"K\n" +
	"\x15ListTelemetryResponse\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.core.v1.TelemetryRecordR\arecords\"\xc1\x01\n" +
	"\x16IngestTelemetryRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\tR\x05msgId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\"K\n" +
	"\x17IngestTelemetryResponse\x120\n" +
	"\x06record\x18\x01 \x01(\v2\x18.core.v1.TelemetryRecordR\x06record\"P\n" +
	"\x16RecordTelemetryRequest\x126\n" +
	"\ttelemetry\x18\x01 \x01(\v2\x18.core.v1.TelemetryRecordR\ttelemetry\"K\n" +
	"\x17RecordTelemetryResponse\x120\n" +
	"\x06record\x18\x01 \x01(\v2\x18.core.v1.TelemetryRecordR\x06record\"j\n" +
	"\x14CreateCommandRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"C\n" +
	"\x15CreateCommandResponse\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.core.v1.CommandR\acommand\"\x15\n" +
	"\x13ListCommandsRequest\"D\n" +
	"\x14ListCommandsResponse\x12,\n" +
	"\bcommands\x18\x01 \x03(\v2\x10.core.v1.CommandR\bcommands\"#\n" +
	"\x11GetCommandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x12GetCommandResponse\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.core.v1.CommandR\acommand\"]\n" +
	"\x11AckCommandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\"@\n" +
	"\x12AckCommandResponse\x12*\n" +
	"\acommand\x18\x01 \x01(\v2\x10.core.v1.CommandR\acommand2\xe0\a\n" +
	"\vCoreService\x12=\n" +
	"\fCreateTenant\x12\x1c.core.v1.CreateTenantRequest\x1a\x0f.core.v1.Tenant\x12H\n" +
	"\vListTenants\x12\x1b.core.v1.ListTenantsRequest\x1a\x1c.core.v1.ListTenantsResponse\x12=\n" +
	"\fCreateDevice\x12\x1c.core.v1.CreateDeviceRequest\x1a\x0f.core.v1.Device\x12H\n" +
	"\vListDevices\x12\x1b.core.v1.ListDevicesRequest\x1a\x1c.core.v1.ListDevicesResponse\x12B\n" +
	"\tGetDevice\x12\x19.core.v1.GetDeviceRequest\x1a\x1a.core.v1.GetDeviceResponse\x12T\n" +
	"\x0fGetDeviceStatus\x12\x1f.core.v1.GetDeviceStatusRequest\x1a .core.v1.GetDeviceStatusResponse\x12N\n" +
	"\rListTelemetry\x12\x1d.core.v1.ListTelemetryRequest\x1a\x1e.core.v1.ListTelemetryResponse\x12T\n" +
	"\x0fIngestTelemetry\x12\x1f.core.v1.IngestTelemetryRequest\x1a .core.v1.IngestTelemetryResponse\x12T\n" +
	"\x0fRecordTelemetry\x12\x1f.core.v1.RecordTelemetryRequest\x1a .core.v1.RecordTelemetryResponse\x12N\n" +
	"\rCreateCommand\x12\x1d.core.v1.CreateCommandRequest\x1a\x1e.core.v1.CreateCommandResponse\x12K\n" +
	"\fListCommands\x12\x1c.core.v1.ListCommandsRequest\x1a\x1d.core.v1.ListCommandsResponse\x12E\n" +
	"\n" +
	"GetCommand\x12\x1a.core.v1.GetCommandRequest\x1a\x1b.core.v1.GetCommandResponse\x12E\n" +
	"\n" +
	"AckCommand\x12\x1a.core.v1.AckCommandRequest\x1a\x1b.core.v1.AckCommandResponseB\x1aZ\x18iot/proto/core/v1;corev1b\x06proto3"

var (
	file_proto_core_v1_core_proto_rawDescOnce sync.Once
	file_proto_core_v1_core_proto_rawDescData []byte
)

func file_proto_core_v1_core_proto_rawDescGZIP() []byte {
	file_proto_core_v1_core_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_core_proto_rawDesc), len(file_proto_core_v1_core_proto_rawDesc)))
	})
	return file_proto_core_v1_core_proto_rawDescData
}

var file_proto_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_core_v1_core_proto_goTypes = []any{
	(*Tenant)(nil),                  // 0: core.v1.Tenant
	(*Device)(nil),                  // 1: core.v1.Device
	(*DeviceStatus)(nil),            // 2: core.v1.DeviceStatus
	(*TelemetryRecord)(nil),         // 3: core.v1.TelemetryRecord
	(*Command)(nil),                 // 4: core.v1.Command
	(*CreateTenantRequest)(nil),     // 5: core.v1.CreateTenantRequest
	(*CreateDeviceRequest)(nil),     // 6: core.v1.CreateDeviceRequest
	(*GetDeviceRequest)(nil),        // 7: core.v1.GetDeviceRequest
	(*GetDeviceResponse)(nil),       // 8: core.v1.GetDeviceResponse
	(*GetDeviceStatusRequest)(nil),  // 9: core.v1.GetDeviceStatusRequest
	(*GetDeviceStatusResponse)(nil), // 10: core.v1.GetDeviceStatusResponse
	(*ListTenantsRequest)(nil),      // 11: core.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),     // 12: core.v1.ListTenantsResponse
	(*ListDevicesRequest)(nil),      // 13: core.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),     // 14: core.v1.ListDevicesResponse
	(*ListTelemetryRequest)(nil),    // 15: core.v1.ListTelemetryRequest
	(*ListTelemetryResponse)(nil),   // 16: core.v1.ListTelemetryResponse
	(*IngestTelemetryRequest)(nil),  // 17: core.v1.IngestTelemetryRequest
	(*IngestTelemetryResponse)(nil), // 18: core.v1.IngestTelemetryResponse
	(*RecordTelemetryRequest)(nil),  // 19: core.v1.RecordTelemetryRequest
	(*RecordTelemetryResponse)(nil), // 20: core.v1.RecordTelemetryResponse
	(*CreateCommandRequest)(nil),    // 21: core.v1.CreateCommandRequest
	(*CreateCommandResponse)(nil),   // 22: core.v1.CreateCommandResponse
	(*ListCommandsRequest)(nil),     // 23: core.v1.ListCommandsRequest
	(*ListCommandsResponse)(nil),    // 24: core.v1.ListCommandsResponse
	(*GetCommandRequest)(nil),       // 25: core.v1.GetCommandRequest
	(*GetCommandResponse)(nil),      // 26: core.v1.GetCommandResponse
	(*AckCommandRequest)(nil),       // 27: core.v1.AckCommandRequest
	(*AckCommandResponse)(nil),      // 28: core.v1.AckCommandResponse
	(*timestamppb.Timestamp)(nil),   // 29: google.protobuf.Timestamp
}
var file_proto_core_v1_core_proto_depIdxs = []int32{
	29, // 0: core.v1.Device.created_at:type_name -> google.protobuf.Timestamp
	29, // 1: core.v1.DeviceStatus.last_seen_at:type_name -> google.protobuf.Timestamp
	29, // 2: core.v1.TelemetryRecord.received_at:type_name -> google.protobuf.Timestamp
	29, // 3: core.v1.Command.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: core.v1.Command.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: core.v1.GetDeviceResponse.device:type_name -> core.v1.Device
	2,  // 6: core.v1.GetDeviceStatusResponse.status:type_name -> core.v1.DeviceStatus
	0,  // 7: core.v1.ListTenantsResponse.tenants:type_name -> core.v1.Tenant
	1,  // 8: core.v1.ListDevicesResponse.devices:type_name -> core.v1.Device
	3,  // 9: core.v1.ListTelemetryResponse.records:type_name -> core.v1.TelemetryRecord
	3,  // 10: core.v1.IngestTelemetryResponse.record:type_name -> core.v1.TelemetryRecord
	3,  // 11: core.v1.RecordTelemetryRequest.telemetry:type_name -> core.v1.TelemetryRecord
	3,  // 12: core.v1.RecordTelemetryResponse.record:type_name -> core.v1.TelemetryRecord
	4,  // 13: core.v1.CreateCommandResponse.command:type_name -> core.v1.Command
	4,  // 14: core.v1.ListCommandsResponse.commands:type_name -> core.v1.Command
	4,  // 15: core.v1.GetCommandResponse.command:type_name -> core.v1.Command
	4,  // 16: core.v1.AckCommandResponse.command:type_name -> core.v1.Command
	5,  // 17: core.v1.CoreService.CreateTenant:input_type -> core.v1.CreateTenantRequest
	11, // 18: core.v1.CoreService.ListTenants:input_type -> core.v1.ListTenantsRequest
	6,  // 19: core.v1.CoreService.CreateDevice:input_type -> core.v1.CreateDeviceRequest
	13, // 20: core.v1.CoreService.ListDevices:input_type -> core.v1.ListDevicesRequest
	7,  // 21: core.v1.CoreService.GetDevice:input_type -> core.v1.GetDeviceRequest
	9,  // 22: core.v1.CoreService.GetDeviceStatus:input_type -> core.v1.GetDeviceStatusRequest
	15, // 23: core.v1.CoreService.ListTelemetry:input_type -> core.v1.ListTelemetryRequest
	17, // 24: core.v1.CoreService.IngestTelemetry:input_type -> core.v1.IngestTelemetryRequest
	19, // 25: core.v1.CoreService.RecordTelemetry:input_type -> core.v1.RecordTelemetryRequest
	21, // 26: core.v1.CoreService.CreateCommand:input_type -> core.v1.CreateCommandRequest
	23, // 27: core.v1.CoreService.ListCommands:input_type -> core.v1.ListCommandsRequest
	25, // 28: core.v1.CoreService.GetCommand:input_type -> core.v1.GetCommandRequest
	27, // 29: core.v1.CoreService.AckCommand:input_type -> core.v1.AckCommandRequest
	0,  // 30: core.v1.CoreService.CreateTenant:output_type -> core.v1.Tenant
	12, // 31: core.v1.CoreService.ListTenants:output_type -> core.v1.ListTenantsResponse
	1,  // 32: core.v1.CoreService.CreateDevice:output_type -> core.v1.Device
	14, // 33: core.v1.CoreService.ListDevices:output_type -> core.v1.ListDevicesResponse
	8,  // 34: core.v1.CoreService.GetDevice:output_type -> core.v1.GetDeviceResponse
	10, // 35: core.v1.CoreService.GetDeviceStatus:output_type -> core.v1.GetDeviceStatusResponse
	16, // 36: core.v1.CoreService.ListTelemetry:output_type -> core.v1.ListTelemetryResponse
	18, // 37: core.v1.CoreService.IngestTelemetry:output_type -> core.v1.IngestTelemetryResponse
	20, // 38: core.v1.CoreService.RecordTelemetry:output_type -> core.v1.RecordTelemetryResponse
	22, // 39: core.v1.CoreService.CreateCommand:output_type -> core.v1.CreateCommandResponse
	24, // 40: core.v1.CoreService.ListCommands:output_type -> core.v1.ListCommandsResponse
	26, // 41: core.v1.CoreService.GetCommand:output_type -> core.v1.GetCommandResponse
	28, // 42: core.v1.CoreService.AckCommand:output_type -> core.v1.AckCommandResponse
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_core_v1_core_proto_init() }
func file_proto_core_v1_core_proto_init() {
	if File_proto_core_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_core_proto_rawDesc), len(file_proto_core_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_core_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_core_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_core_proto_msgTypes,
	}.Build()
	File_proto_core_v1_core_proto = out.File
	file_proto_core_v1_core_proto_goTypes = nil
	file_proto_core_v1_core_proto_depIdxs = nil
}
